<?php
/**
 * @package app\install\acl_role\incl
 * @author Ryno Van Zyl
 * @copyright Copyright Liquid Edge Solutions. All rights reserved.
 */
define("ACL_CODE_DEV", "DEV");
define("ACL_CODE_ADMIN", "ADMIN");
define("ACL_CODE_ADMIN_SUPPORT", "ADMIN_SUPPORT");
define("ACL_CODE_AGENT", "AGENT");
define("ACL_CODE_AGENT_OFFICE_MANAGER", "AGENT_OFFICE_MANAGER");
define("ACL_CODE_AGENT_OWNER", "AGENT_OWNER");
define("ACL_CODE_AGENT_SENIOR", "AGENT_SENIOR");
define("ACL_CODE_AGENT_SUPER_ADMIN", "AGENT_SUPER_ADMIN");
define("ACL_CODE_BRANCH", "BRANCH");
define("ACL_CODE_BRANCH_ADMIN", "BRANCH_ADMIN");
define("ACL_CODE_BRANCH_EMPLOYEE", "BRANCH_EMPLOYEE");
define("ACL_CODE_CLIENT", "CLIENT");
define("ACL_CODE_CONTACT_PERSON", "CONTACT_PERSON");
define("ACL_CODE_EVENT_COORDINATOR", "EVENT_COORDINATOR");
define("ACL_CODE_FACILITY_OCCUPANT", "FACILITY_OCCUPANT");
define("ACL_CODE_LEAD", "LEAD");
define("ACL_CODE_PROPERTY_LANDLORD", "PROPERTY_LANDLORD");
define("ACL_CODE_PROPERTY_SELLER", "PROPERTY_SELLER");
define("ACL_CODE_PROPERTY_TENANT", "PROPERTY_TENANT");
define("ACL_CODE_PROVIDER", "PROVIDER");
define("ACL_CODE_SALES_REP", "SALES_REP");
define("ACL_CODE_SEO", "SEO");
define("ACL_CODE_STAFF_MEMBER", "STAFF_MEMBER");
define("ACL_CODE_STORE_MANAGER", "STORE_MANAGER");
define("ACL_CODE_SUBSCRIBER", "SUBSCRIBER");
define("ACL_CODE_SUPERADMIN", "SUPERADMIN");
define("ACL_CODE_USER", "USER");
define("ACL_CODE_WAREHOUSE", "WAREHOUSE");
define("ACL_AUTH_USERS", [ACL_CODE_DEV, ACL_CODE_ADMIN, ACL_CODE_ADMIN_SUPPORT, ACL_CODE_AGENT, ACL_CODE_AGENT_OFFICE_MANAGER, ACL_CODE_AGENT_OWNER, ACL_CODE_AGENT_SENIOR, ACL_CODE_AGENT_SUPER_ADMIN, ACL_CODE_BRANCH, ACL_CODE_BRANCH_ADMIN, ACL_CODE_BRANCH_EMPLOYEE, ACL_CODE_CLIENT, ACL_CODE_CONTACT_PERSON, ACL_CODE_EVENT_COORDINATOR, ACL_CODE_FACILITY_OCCUPANT, ACL_CODE_LEAD, ACL_CODE_PROPERTY_LANDLORD, ACL_CODE_PROPERTY_SELLER, ACL_CODE_PROPERTY_TENANT, ACL_CODE_PROVIDER, ACL_CODE_SALES_REP, ACL_CODE_SEO, ACL_CODE_STAFF_MEMBER, ACL_CODE_STORE_MANAGER, ACL_CODE_SUBSCRIBER, ACL_CODE_SUPERADMIN, ACL_CODE_USER, ACL_CODE_WAREHOUSE]);

